version: "3.3"

services:

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5432:5432
    networks:
      - transcendence


  ## Build backend
  #test:
  #  build:
  #    context: backend
  #    dockerfile: Dockerfile
  #  image: testimage
  #  restart: always
  #  #command: sh -c 'sleep 10000000000000000000'
  #  #command: sh -c './start.sh dev'
  #  working_dir: /backend
  #  environment:
  #    GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  #    GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  #    INTRA_CLIENT_ID: "${INTRA_CLIENT_ID}"
  #    INTRA_CLIENT_SECRET: "${INTRA_CLIENT_SECRET}"
  #    JWT_SECRET: "${JWT_SECRET}"
  #    DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}?schema=public"
  #  volumes:
  #    - ./backend:/backend
  #    - ./avatars:/backend/avatars
  #  depends_on:
  #    - db
  #  networks:
  #    - transcendence
  #  ports:
  #    - 3002:3000


  #testfrontend:
  #  build:
  #    context: frontend
  #    dockerfile: Dockerfile
  #  image: testimagefronted
  #  restart: always
  #  command:  sh -c './start.sh dev'
  #  working_dir: /frontend
  #  volumes:
  #    - ./frontend:/frontend
  #    - ./avatars:/frontend/public/avatars
  #  depends_on:
  #    - db
  #  ports:
  #    - 3003:3000
  #    #- 24678:24678 # For HMR
  #  environment:
  #    HOST: 0.0.0.0
  #    GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  #    INTRA_CLIENT_ID: "${INTRA_CLIENT_ID}"
  #    BACKEND_URL: http://localhost:3001
  #    BACKEND_API_VERSION: /api/v0
    
  #  networks:
  #    - transcendence

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    working_dir: /backend
    command:  sh -c './start.sh dev'
    environment:
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      INTRA_CLIENT_ID: "${INTRA_CLIENT_ID}"
      INTRA_CLIENT_SECRET: "${INTRA_CLIENT_SECRET}"
      JWT_SECRET: "${JWT_SECRET}"
      BACKEND_IP: "${BACKEND_IP}"
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_USER}?schema=public"
    volumes:
      - ./backend:/backend
      - ./avatars:/backend/avatars
    depends_on:
      - db
    ports:
      - 3001:3000
      - 5555:5555
    networks:
      - transcendence

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always

    command:  sh -c './start.sh dev'
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
      - ./avatars:/frontend/public/avatars
    depends_on:
      - db
    ports:
      - 3000:3000
      - 24678:24678 # For HMR
    environment:
      HOST: 0.0.0.0
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      INTRA_CLIENT_ID: "${INTRA_CLIENT_ID}"
      BACKEND_URL: "http://${BACKEND_IP}:3001"
      BACKEND_API_VERSION: /api/v0
    
    networks:
      - transcendence

volumes:
  db-data:
    driver: local

networks:
  transcendence:
    driver: bridge